# Generated by Django 5.2.14 on 2026-06-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0004_remove_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='witnessstatement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='witness_photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
        migrations.CreateModel(
            name='AccidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accident_photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accidents.accident', verbose_name='ДТП')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_accident_photos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='accidents.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фотография ДТП',
                'verbose_name_plural': 'Фотографии ДТП',
                'ordering': ['-created_at'],
            },
        ),
    ]
